apiVersion: v1
kind: Secret
metadata:
  name: example-app-repo
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:GuardX10/example-helm-chart.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDzjGxpya10i55bPoDZZKqc4RZ3fIDJSE5XBWKItE7zrAAAAKBmSmu4Zkpr
    uAAAAAtzc2gtZWQyNTUxOQAAACDzjGxpya10i55bPoDZZKqc4RZ3fIDJSE5XBWKItE7zrA
    AAAEBNPmWyCEdq7aUA7LSkU4bEbQ4IrerwHDCcrcaDVzYaMvOMbGnJrXSLnls+gNlkqpzh
    Fnd8gMlITlcFYoi0TvOsAAAAGG9sZWtzaWlAZGV2b3BzY29tcGFueS5ubAECAwQF
    -----END OPENSSH PRIVATE KEY-----